// DO NOT EDIT. generated by github.com/tinywasm/orm

package itemcatalog

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type CatalogItem struct {
	Id string
	TenantId string
	Sku string
	Name string
	Description string
	Category string
	Type string
	Price float64
	Currency string
	IsActive bool
	UpdatedAt int64
}

func (m *CatalogItem) ModelName() string { return "catalog_item" }

func (m *CatalogItem) Schema() []model.Field { return CatalogItemModel.Fields }

func (m *CatalogItem) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Sku, &m.Name, &m.Description, &m.Category, &m.Type, &m.Price, &m.Currency, &m.IsActive, &m.UpdatedAt} }

func (m *CatalogItem) IsNil() bool { return m == nil }

func (m *CatalogItem) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("sku", m.Sku)
	w.String("name", m.Name)
	if m.Description != "" { w.String("description", m.Description) }
	if m.Category != "" { w.String("category", m.Category) }
	w.String("type", m.Type)
	w.Float("price", m.Price)
	w.String("currency", m.Currency)
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *CatalogItem) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("sku"); ok { m.Sku = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("description"); ok { m.Description = v }
	if v, ok := r.String("category"); ok { m.Category = v }
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.Float("price"); ok { m.Price = v }
	if v, ok := r.String("currency"); ok { m.Currency = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type CatalogItemList []*CatalogItem

func (s *CatalogItemList) Schema() []model.Field { return nil }
func (s *CatalogItemList) Pointers() []any     { return nil }
func (s *CatalogItemList) Len() int             { return len(*s) }
func (s *CatalogItemList) At(i int) model.Fielder { return (*s)[i] }
func (s *CatalogItemList) Append() model.Fielder  { v := &CatalogItem{}; *s = append(*s, v); return v }
func (s *CatalogItemList) IsNil() bool          { return s == nil }
func (s *CatalogItemList) EncodeFields(_ model.FieldWriter) {}
func (s *CatalogItemList) DecodeFields(_ model.FieldReader) {}

func (m *CatalogItem) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var CatalogItem_ = struct {
	Id string
	TenantId string
	Sku string
	Name string
	Description string
	Category string
	Type string
	Price string
	Currency string
	IsActive string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Sku: "sku",
	Name: "name",
	Description: "description",
	Category: "category",
	Type: "type",
	Price: "price",
	Currency: "currency",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneCatalogItem(qb *orm.QB, model *CatalogItem) (*CatalogItem, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllCatalogItem(qb *orm.QB) (CatalogItemList, error) {
	var results CatalogItemList
	err := qb.ReadAll(
		func() model.Model { return &CatalogItem{} },
		func(m model.Model) { results = append(results, m.(*CatalogItem)) },
	)
	return results, err
}

type Agreement struct {
	Id string
	TenantId string
	CatalogItemId string
	Insurer string
	Code string
	Price float64
	IsActive bool
	UpdatedAt int64
}

func (m *Agreement) ModelName() string { return "catalog_agreement" }

func (m *Agreement) Schema() []model.Field { return AgreementModel.Fields }

func (m *Agreement) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.CatalogItemId, &m.Insurer, &m.Code, &m.Price, &m.IsActive, &m.UpdatedAt} }

func (m *Agreement) IsNil() bool { return m == nil }

func (m *Agreement) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("catalog_item_id", m.CatalogItemId)
	w.String("insurer", m.Insurer)
	if m.Code != "" { w.String("code", m.Code) }
	if m.Price != 0 { w.Float("price", m.Price) }
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Agreement) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("catalog_item_id"); ok { m.CatalogItemId = v }
	if v, ok := r.String("insurer"); ok { m.Insurer = v }
	if v, ok := r.String("code"); ok { m.Code = v }
	if v, ok := r.Float("price"); ok { m.Price = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type AgreementList []*Agreement

func (s *AgreementList) Schema() []model.Field { return nil }
func (s *AgreementList) Pointers() []any     { return nil }
func (s *AgreementList) Len() int             { return len(*s) }
func (s *AgreementList) At(i int) model.Fielder { return (*s)[i] }
func (s *AgreementList) Append() model.Fielder  { v := &Agreement{}; *s = append(*s, v); return v }
func (s *AgreementList) IsNil() bool          { return s == nil }
func (s *AgreementList) EncodeFields(_ model.FieldWriter) {}
func (s *AgreementList) DecodeFields(_ model.FieldReader) {}

func (m *Agreement) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Agreement_ = struct {
	Id string
	TenantId string
	CatalogItemId string
	Insurer string
	Code string
	Price string
	IsActive string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	CatalogItemId: "catalog_item_id",
	Insurer: "insurer",
	Code: "code",
	Price: "price",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneAgreement(qb *orm.QB, model *Agreement) (*Agreement, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllAgreement(qb *orm.QB) (AgreementList, error) {
	var results AgreementList
	err := qb.ReadAll(
		func() model.Model { return &Agreement{} },
		func(m model.Model) { results = append(results, m.(*Agreement)) },
	)
	return results, err
}

func (m *Agreement) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: AgreementModel.Fields[2], Ref: "catalog_item", RefColumn: "id", OnDelete: ""},
	}
}

type ItemFilter struct {
	Type string
	ActiveOnly bool
	Limit int64
	Offset int64
}

func (m *ItemFilter) ModelName() string { return "item_filter" }

func (m *ItemFilter) Schema() []model.Field { return ItemFilterModel.Fields }

func (m *ItemFilter) Pointers() []any { return []any{&m.Type, &m.ActiveOnly, &m.Limit, &m.Offset} }

func (m *ItemFilter) IsNil() bool { return m == nil }

func (m *ItemFilter) EncodeFields(w model.FieldWriter) {
	w.String("type", m.Type)
	w.Bool("active_only", m.ActiveOnly)
	w.Int("limit", m.Limit)
	w.Int("offset", m.Offset)
}

func (m *ItemFilter) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.Bool("active_only"); ok { m.ActiveOnly = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
	if v, ok := r.Int("offset"); ok { m.Offset = v }
}

type ItemFilterList []*ItemFilter

func (s *ItemFilterList) Schema() []model.Field { return nil }
func (s *ItemFilterList) Pointers() []any     { return nil }
func (s *ItemFilterList) Len() int             { return len(*s) }
func (s *ItemFilterList) At(i int) model.Fielder { return (*s)[i] }
func (s *ItemFilterList) Append() model.Fielder  { v := &ItemFilter{}; *s = append(*s, v); return v }
func (s *ItemFilterList) IsNil() bool          { return s == nil }
func (s *ItemFilterList) EncodeFields(_ model.FieldWriter) {}
func (s *ItemFilterList) DecodeFields(_ model.FieldReader) {}

type ListItemsArgs struct {
	TenantId string
	Type string
	ActiveOnly bool
	Limit int64
	Offset int64
}

func (m *ListItemsArgs) ModelName() string { return "list_items_args" }

func (m *ListItemsArgs) Schema() []model.Field { return ListItemsArgsModel.Fields }

func (m *ListItemsArgs) Pointers() []any { return []any{&m.TenantId, &m.Type, &m.ActiveOnly, &m.Limit, &m.Offset} }

func (m *ListItemsArgs) IsNil() bool { return m == nil }

func (m *ListItemsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("type", m.Type)
	w.Bool("active_only", m.ActiveOnly)
	w.Int("limit", m.Limit)
	w.Int("offset", m.Offset)
}

func (m *ListItemsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.Bool("active_only"); ok { m.ActiveOnly = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
	if v, ok := r.Int("offset"); ok { m.Offset = v }
}

type ListItemsArgsList []*ListItemsArgs

func (s *ListItemsArgsList) Schema() []model.Field { return nil }
func (s *ListItemsArgsList) Pointers() []any     { return nil }
func (s *ListItemsArgsList) Len() int             { return len(*s) }
func (s *ListItemsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListItemsArgsList) Append() model.Fielder  { v := &ListItemsArgs{}; *s = append(*s, v); return v }
func (s *ListItemsArgsList) IsNil() bool          { return s == nil }
func (s *ListItemsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListItemsArgsList) DecodeFields(_ model.FieldReader) {}

type GetItemArgs struct {
	TenantId string
	Id string
}

func (m *GetItemArgs) ModelName() string { return "get_item_args" }

func (m *GetItemArgs) Schema() []model.Field { return GetItemArgsModel.Fields }

func (m *GetItemArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *GetItemArgs) IsNil() bool { return m == nil }

func (m *GetItemArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetItemArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetItemArgsList []*GetItemArgs

func (s *GetItemArgsList) Schema() []model.Field { return nil }
func (s *GetItemArgsList) Pointers() []any     { return nil }
func (s *GetItemArgsList) Len() int             { return len(*s) }
func (s *GetItemArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetItemArgsList) Append() model.Fielder  { v := &GetItemArgs{}; *s = append(*s, v); return v }
func (s *GetItemArgsList) IsNil() bool          { return s == nil }
func (s *GetItemArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetItemArgsList) DecodeFields(_ model.FieldReader) {}

type FindBySKUArgs struct {
	TenantId string
	Sku string
}

func (m *FindBySKUArgs) ModelName() string { return "find_by_sku_args" }

func (m *FindBySKUArgs) Schema() []model.Field { return FindBySKUArgsModel.Fields }

func (m *FindBySKUArgs) Pointers() []any { return []any{&m.TenantId, &m.Sku} }

func (m *FindBySKUArgs) IsNil() bool { return m == nil }

func (m *FindBySKUArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("sku", m.Sku)
}

func (m *FindBySKUArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("sku"); ok { m.Sku = v }
}

type FindBySKUArgsList []*FindBySKUArgs

func (s *FindBySKUArgsList) Schema() []model.Field { return nil }
func (s *FindBySKUArgsList) Pointers() []any     { return nil }
func (s *FindBySKUArgsList) Len() int             { return len(*s) }
func (s *FindBySKUArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *FindBySKUArgsList) Append() model.Fielder  { v := &FindBySKUArgs{}; *s = append(*s, v); return v }
func (s *FindBySKUArgsList) IsNil() bool          { return s == nil }
func (s *FindBySKUArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *FindBySKUArgsList) DecodeFields(_ model.FieldReader) {}

type DeactivateItemArgs struct {
	TenantId string
	Id string
}

func (m *DeactivateItemArgs) ModelName() string { return "deactivate_item_args" }

func (m *DeactivateItemArgs) Schema() []model.Field { return DeactivateItemArgsModel.Fields }

func (m *DeactivateItemArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeactivateItemArgs) IsNil() bool { return m == nil }

func (m *DeactivateItemArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeactivateItemArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeactivateItemArgsList []*DeactivateItemArgs

func (s *DeactivateItemArgsList) Schema() []model.Field { return nil }
func (s *DeactivateItemArgsList) Pointers() []any     { return nil }
func (s *DeactivateItemArgsList) Len() int             { return len(*s) }
func (s *DeactivateItemArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeactivateItemArgsList) Append() model.Fielder  { v := &DeactivateItemArgs{}; *s = append(*s, v); return v }
func (s *DeactivateItemArgsList) IsNil() bool          { return s == nil }
func (s *DeactivateItemArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeactivateItemArgsList) DecodeFields(_ model.FieldReader) {}

type DeleteItemArgs struct {
	TenantId string
	Id string
}

func (m *DeleteItemArgs) ModelName() string { return "delete_item_args" }

func (m *DeleteItemArgs) Schema() []model.Field { return DeleteItemArgsModel.Fields }

func (m *DeleteItemArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteItemArgs) IsNil() bool { return m == nil }

func (m *DeleteItemArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteItemArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteItemArgsList []*DeleteItemArgs

func (s *DeleteItemArgsList) Schema() []model.Field { return nil }
func (s *DeleteItemArgsList) Pointers() []any     { return nil }
func (s *DeleteItemArgsList) Len() int             { return len(*s) }
func (s *DeleteItemArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteItemArgsList) Append() model.Fielder  { v := &DeleteItemArgs{}; *s = append(*s, v); return v }
func (s *DeleteItemArgsList) IsNil() bool          { return s == nil }
func (s *DeleteItemArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteItemArgsList) DecodeFields(_ model.FieldReader) {}

type ListAgreementsArgs struct {
	TenantId string
	CatalogItemId string
}

func (m *ListAgreementsArgs) ModelName() string { return "list_agreements_args" }

func (m *ListAgreementsArgs) Schema() []model.Field { return ListAgreementsArgsModel.Fields }

func (m *ListAgreementsArgs) Pointers() []any { return []any{&m.TenantId, &m.CatalogItemId} }

func (m *ListAgreementsArgs) IsNil() bool { return m == nil }

func (m *ListAgreementsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("catalog_item_id", m.CatalogItemId)
}

func (m *ListAgreementsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("catalog_item_id"); ok { m.CatalogItemId = v }
}

type ListAgreementsArgsList []*ListAgreementsArgs

func (s *ListAgreementsArgsList) Schema() []model.Field { return nil }
func (s *ListAgreementsArgsList) Pointers() []any     { return nil }
func (s *ListAgreementsArgsList) Len() int             { return len(*s) }
func (s *ListAgreementsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListAgreementsArgsList) Append() model.Fielder  { v := &ListAgreementsArgs{}; *s = append(*s, v); return v }
func (s *ListAgreementsArgsList) IsNil() bool          { return s == nil }
func (s *ListAgreementsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListAgreementsArgsList) DecodeFields(_ model.FieldReader) {}

type DeleteAgreementArgs struct {
	TenantId string
	Id string
}

func (m *DeleteAgreementArgs) ModelName() string { return "delete_agreement_args" }

func (m *DeleteAgreementArgs) Schema() []model.Field { return DeleteAgreementArgsModel.Fields }

func (m *DeleteAgreementArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteAgreementArgs) IsNil() bool { return m == nil }

func (m *DeleteAgreementArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteAgreementArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteAgreementArgsList []*DeleteAgreementArgs

func (s *DeleteAgreementArgsList) Schema() []model.Field { return nil }
func (s *DeleteAgreementArgsList) Pointers() []any     { return nil }
func (s *DeleteAgreementArgsList) Len() int             { return len(*s) }
func (s *DeleteAgreementArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteAgreementArgsList) Append() model.Fielder  { v := &DeleteAgreementArgs{}; *s = append(*s, v); return v }
func (s *DeleteAgreementArgsList) IsNil() bool          { return s == nil }
func (s *DeleteAgreementArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteAgreementArgsList) DecodeFields(_ model.FieldReader) {}
