// DO NOT EDIT. generated by github.com/tinywasm/orm

package itemcatalog

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

var _schemaCatalogItem = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "tenant_id", Type: fmt.FieldText, NotNull: true},
		{Name: "sku", Type: fmt.FieldText, NotNull: true},
		{Name: "name", Type: fmt.FieldText, NotNull: true},
		{Name: "description", Type: fmt.FieldText},
		{Name: "type", Type: fmt.FieldText, NotNull: true},
		{Name: "price", Type: fmt.FieldFloat, NotNull: true},
		{Name: "currency", Type: fmt.FieldText, NotNull: true},
		{Name: "is_active", Type: fmt.FieldBool, NotNull: true},
		{Name: "updated_at", Type: fmt.FieldInt, NotNull: true},
	}

func (m *CatalogItem) Schema() []fmt.Field { return _schemaCatalogItem }

func (m *CatalogItem) Pointers() []any {
	return []any{
		&m.ID,
		&m.TenantID,
		&m.SKU,
		&m.Name,
		&m.Description,
		&m.Type,
		&m.Price,
		&m.Currency,
		&m.IsActive,
		&m.UpdatedAt,
	}
}

func (m *CatalogItem) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var CatalogItem_ = struct {
	ModelName string
	ID string
	TenantID string
	SKU string
	Name string
	Description string
	Type string
	Price string
	Currency string
	IsActive string
	UpdatedAt string
}{
	ModelName: "catalog_item",
	ID: "id",
	TenantID: "tenant_id",
	SKU: "sku",
	Name: "name",
	Description: "description",
	Type: "type",
	Price: "price",
	Currency: "currency",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneCatalogItem(qb *orm.QB, model *CatalogItem) (*CatalogItem, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllCatalogItem(qb *orm.QB) ([]*CatalogItem, error) {
	var results []*CatalogItem
	err := qb.ReadAll(
		func() fmt.Model { return &CatalogItem{} },
		func(m fmt.Model) { results = append(results, m.(*CatalogItem)) },
	)
	return results, err
}

func (m *ItemFilter) ModelName() string {
	return "item_filter"
}

var _schemaItemFilter = []fmt.Field{
		{Name: "type", Type: fmt.FieldText},
		{Name: "active_only", Type: fmt.FieldBool},
		{Name: "limit", Type: fmt.FieldInt},
		{Name: "offset", Type: fmt.FieldInt},
	}

func (m *ItemFilter) Schema() []fmt.Field { return _schemaItemFilter }

func (m *ItemFilter) Pointers() []any {
	return []any{
		&m.Type,
		&m.ActiveOnly,
		&m.Limit,
		&m.Offset,
	}
}

var ItemFilter_ = struct {
	ModelName string
	Type string
	ActiveOnly string
	Limit string
	Offset string
}{
	ModelName: "item_filter",
	Type: "type",
	ActiveOnly: "active_only",
	Limit: "limit",
	Offset: "offset",
}

func ReadOneItemFilter(qb *orm.QB, model *ItemFilter) (*ItemFilter, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllItemFilter(qb *orm.QB) ([]*ItemFilter, error) {
	var results []*ItemFilter
	err := qb.ReadAll(
		func() fmt.Model { return &ItemFilter{} },
		func(m fmt.Model) { results = append(results, m.(*ItemFilter)) },
	)
	return results, err
}
